apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - configmap.yaml
  - secret.yaml

commonLabels:
  app: vote-app
  environment: production