apiVersion: v1
kind: Service
metadata:
  name: vote-app
  labels:
    app: vote-app
spec:
  ports:
  - port: 80
    targetPort: 3000
    name: http
  - port: 3001
    targetPort: 3001
    name: api
  selector:
    app: vote-app
  type: ClusterIP